---
- name: CLI tools
  become: yes
  become_user: root
  block:
    - name: Ensure net-tools is present
      apt:
        name: net-tools
        state: present

    - name: Ensure tmux is present
      apt:
        name: tmux
        state: present

    - name: Ensure vim is present
      apt:
        name: vim
        state: present

    - name: Ensure zsh is present
      apt:
        name: zsh
        state: present

    - name: Ensure devuser default shell is zsh
      user:
        name: devuser
        shell: /usr/bin/zsh