---
- name: Ensuring lightweight GUI is present (openbox xorg)
  become: yes
  become_user: root
  block:
    - name: Install xorg
      apt:
        name: xorg
        state: present

    - name: Install openbox without recommends
      apt:
        name: openbox
        state: present
        install_recommends: no

    - name: Install firefox
      apt:
        name: firefox
        state: present

    - name: Set x-www-browser to firefox
      community.general.alternatives:
        name: x-www-browser
        path: /usr/bin/firefox
        priority: 50
