---
- name: Podman
  become: yes
  become_user: root
  block:
    - name: Ensure podman packages are present
      apt:
        name:
          - podman
          - podman-compose
        state: present


    - name: Ensure podman-docker is NOT installed (no docker alias)
      apt:
        name: podman-docker
        state: absent
