---
- name: SSH
  become: yes
  become_user: root
  block:
    - name: Ensure openssh-server is installed
      apt:
        name: openssh-server
        state: present

    - name: Ensure passwordless SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"

    - name: Ensure public key authentication is enabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PubkeyAuthentication"
        line: "PubkeyAuthentication yes"

    - name: Ensure devuser .ssh directory exists
      file:
        path: /home/devuser/.ssh
        state: directory
        mode: "0700"
        owner: devuser
        group: devuser

    - name: Ensure devuser authorized_keys is present
      copy:
        src: ../files/authorized_keys
        dest: /home/devuser/.ssh/authorized_keys
        mode: "0600"
        owner: devuser
        group: devuser

    - name: Check if systemd is available
      ansible.builtin.stat:
        path: /run/systemd/system
      register: systemd_check

    - name: Ensure sshd is enabled and running at boot
      systemd:
        name: sshd
        state: restarted
        enabled: yes
        daemon_reload: yes
      when: systemd_check.stat.exists