---
- name: Configure devuser
  hosts: local
  become: yes
  become_user: devuser
  gather_facts: yes

  tasks:
    - name: Include install_gui tasks
      ansible.builtin.import_tasks: ../tasks/provision/install_gui.yml
