---
- name: Configure devuser
  hosts: local
  become: yes
  become_user: devuser
  gather_facts: yes

  tasks:
    - name: Include cli tasks
      ansible.builtin.import_tasks: ../tasks/provision/cli.yml
    - name: Include podman tasks
      ansible.builtin.import_tasks: ../tasks/provision/podman.yml
    - name: Include pi.dev tasks
      ansible.builtin.import_tasks: ../tasks/provision/pi.dev.yml
    - name: Include sshd tasks
      ansible.builtin.import_tasks: ../tasks/provision/sshd.yml
    - name: Include gui tasks
      ansible.builtin.import_tasks: ../tasks/provision/gui.yml