---
- name: Bootstrap Ubuntu Server
  hosts: local
  become: yes
  gather_facts: yes

  tasks:
    - name: apt_upgrade
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        cache_valid_time: 3600
