---
- name: Bootstrap Ubuntu Server
  hosts: local
  become: yes
  gather_facts: yes

  tasks:
    - name: Include apt_upgrade tasks
      ansible.builtin.import_tasks: ../tasks/apt_upgrade.yml

    - name: Include create_devuser tasks
      ansible.builtin.import_tasks: ../tasks/create_devuser.yml
